### ISSUE TITLE
关闭标签用到的remove方法，IE不支持，可以修复一下吗

### ISSUE THREAD

**Issue by xxgo1992** [alexqdjay/vue-tabs#4]
### vue-tabs version 
0.2.0

### Browser information

IE 11
### What is actually happening?
对象不支持“remove”属性或方法
### Your Codes

``` html
<!--put your code here-->
```

**Comment by alexqdjay** [comment]
不好意思回复有点晚了。
请问修复了么？如果修复了可以提交PR
没有的话，我先看下，一直mac开发确实没有使用IE11测试过

**Comment by alexqdjay** [comment]
已修复 v0.2.1
