### ISSUE TITLE
请教一个关于使用动态加载的问题

### ISSUE THREAD

**Issue by linusok** [alexqdjay/vue-tabs#6]
### vue-tabs version
0.2.1

### Your Codes

``` html
<!--put your code here-->
```

我曾经在vue官方论坛上问过，但没有解决方案：
https://forum.vuejs.org/t/topic/18991

这里我在补充描述下：
我看到vue-tabs组件，跟我目前开发的产品应用场景非常契合，但对于菜单全部是后台表自定义的，与页面组件间关系也是自定义的，所以想请教这个菜单点击后如何动态通过axios.get从服务器上读取一个page1.vue来展示在页签里？

**Comment by alexqdjay** [comment]
https://github.com/alexqdjay/vue-tabs/blob/master/docs/zh-cn/lazy_loading.md

请看这里，懒加载（lazy load），是不是可以帮到你。

**Comment by linusok** [comment]
@alexqdjay 感谢解答，但用你的方法试了，没有得到预期效果，是否还需要在webpack的配置上做文章？
还是说只要用了require.ensure，webpack编译时自己可以识别这一块文件内容需要延迟加载？
我一直未能得到想要的结果，是否可以在您example目录里的tabs.js里，你写个类似我这个需求的异步组件加载显示的效果？
您现在的示例里是使用template(html string）来实现的，但我们通常复杂的页面不可能只有html string的页面，所以如果能实现异步加载vue的单文件组件最好了，谢谢哈。
![image](https://user-images.githubusercontent.com/9760598/31313977-25ad317c-ac26-11e7-89a0-e63c91ee3e04.png)

**Comment by alexqdjay** [comment]
我的example里已经有了，叫异步加载

**Comment by linusok** [comment]
@alexqdjay 哦，我没有说明白，你那个示例只是一个html字符串片段，不是一个完整的(*.vue)的单文件组件，所以还是没有搞明白单文件组件是如何异步的，因为刚学习这个，可能好多基础不清楚，不好意思。

**Comment by alexqdjay** [comment]
更新下master， 注意最新的提交，已经分离出异步的vue
webpack会识别出需要异步的组件文件进行异步加载

**Comment by alexqdjay** [comment]
解决了么? 解决了我就关了

**Comment by linusok** [comment]
@alexqdjay 不好意思，最近出差了一阵子，没有上这里来，你新增加的示例，解决了我的疑问，十分感谢。

**Comment by linusok** [comment]
回答快了，晕，实际编译尝试后，仍然不行。奇怪了。

**Comment by linusok** [comment]
![image](https://user-images.githubusercontent.com/9760598/31771337-53a41014-b50e-11e7-8e78-19cf67a36fba.png)
![image](https://user-images.githubusercontent.com/9760598/31771346-5e4bd074-b50e-11e7-855f-04b4467d8485.png)
![image](https://user-images.githubusercontent.com/9760598/31771357-68c6c3f6-b50e-11e7-9c8c-4d0fe4cb8043.png)
看上去代码执行到了，log输出了，并且组件的文件0.js也请求了，就是没效果。

**Comment by alexqdjay** [comment]
把你的代码传到github上给我地址，我看下
