### ISSUE TITLE
很抱歉，请帮看下异步组件的问题

### ISSUE THREAD

**Issue by linusok** [alexqdjay/vue-tabs#8]
### 我的代码
https://github.com/linusok/vuespa1

#6 接上一次请教动态加载的问题，帮忙看下是哪里问题。不好意思拖了这么久。

主要帮忙看下左侧菜单【库存管理】为啥异步加载不了组件

**Comment by alexqdjay** [comment]
webpack2.x 以后异步返回的东西变了，所以webpack2就不行了

你把vue-tabs 更新到v0.3.0 就可以了
